package be.kuleuven.sessylibrary.domain;

import java.util.Arrays;
import java.util.List;

public final class FavoriteBooks {

    public static List<Book> WoutersFavorites() {
        return Arrays.asList(
                new Book(471168572, "Bread: A Baker's Book of Techniques and Recipes", "Jeffrey Hamelman", "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348888456l/153240.jpg", "The warm, complex aroma of a fresh-baked loaf of bread can be utterly tantalizing; the first bite, a revelation. In Bread: A Baker's Book of Techniques and Recipes, award-winning master baker Jeffrey Hamelman presents the definitive, one-stop reference on the art and science of bread baking - a kitchen essential for seasoned home bakers and professionals alike. Hamelman, a professional baker for nearly three decades, was a member of the United States national baking team that won first place in the 1996 Coupe du Monde de la Boulangerie, the bread-baking World Cup. Here, he shares this experience, putting world-class artisanal loaves within reach of any serious baker. Opening with a comprehensive overview of the foundations - essential ingredients; hand techniques for kneading, scoring, and shaping; the basic process from mixing through baking - he lucidly guides bakers through all elements of this richly rewarding craft. Bread contains 118 detailed, step-by-step recipes for an array of breads: versatile sourdough ryes; breads made with pre-ferments; and simple, straight dough loaves. Recipes for brioche, focaccia, pizza dough, flat breads, and other traditional baking staples augment the diverse collection of flavors, tastes, and textures represented within these pages. From the delicate flavor and aroma of classic French baguettes to the mellow smoothness of Roasted Garlic Levain, a bread for every season and every palate is here.\n" +
                "\n" +
                "Each recipe clearly outlines the key stages, with easy-to-use charts that list ingredients in both American and metric measures, quantities appropriate for home baking, and baker's percentages. Hundreds of drawings vividly illustrate techniques, and 35 handsome color photographs display finished breads. Sidebars accompany each recipe and section with valuable tips, from the subtle art of tasting and evaluating breads to the perfect fare to complement Vollkornbrot. A complete chapter on decorative breads - with instructions on techniques as well as a wide variety of exquisite patterns - will inspire magnificent display creations.\n" +
                "\n" +
                "Laced throughout the book, Hamelman's personal narratives offer a compelling portrait of a lifelong love affair with bread and vividly communicate this passion. For bakers seeking to finesse this time-honored craft or simply to learn the tricks of the trade from a real master, Bread is a resource to be consulted time and time again."),
            new Book(1452126461, "Bar Tartine: Techniques and Flavors", "Nicolaus Balla, Cortney Burns, Jan Newberry", "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1409607857l/20980942.jpg", "Here's a cookbook destined to be talked-about this season, rich in techniques and recipes epitomizing the way we cook and eat now. Bar Tartine--co-founded by Tartine Bakery's Chad Robertson and Elisabeth Prueitt--is obsessed over by locals and visitors, critics and chefs. It is a restaurant that defies categorization, but not description: Everything is made in-house and layered into extraordinarily flavorful food. Helmed by Nick Balla and Cortney Burns, it draws on time-honored processes (such as fermentation, curing, pickling), and a core that runs through the cuisines of Central Europe, Japan, and Scandinavia to deliver a range of dishes from soups to salads, to shared plates and sweets. With more than 150 photographs, this highly anticipated cookbook is a true original"),
            new Book(160358286, "The Art of Fermentation: An in-Depth Exploration of Essential Concepts and Processes from Around the World", "Sandor Ellix Katz", "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1334185796l/13598307.jpg", "Winner of the 2013 James Beard Foundation Book Award for Reference and Scholarship, and a New York Times bestseller, The Art of Fermentation is the most comprehensive guide to do-it-yourself home fermentation ever published. Sandor Katz presents the concepts and processes behind fermentation in ways that are simple enough to guide a reader through their first experience making sauerkraut or yogurt, and in-depth enough to provide greater understanding and insight for experienced practitioners.\n" +
                "\n" +
                "While Katz expertly contextualizes fermentation in terms of biological and cultural evolution, health and nutrition, and even economics, this is primarily a compendium of practical information--how the processes work; parameters for safety; techniques for effective preservation; troubleshooting; and more.\n" +
                "\n" +
                "With two-color illustrations and extended resources, this book provides essential wisdom for cooks, homesteaders, farmers, gleaners, foragers, and food lovers of any kind who want to develop a deeper understanding and appreciation for arguably the oldest form of food preservation, and part of the roots of culture itself.\n" +
                "\n" +
                "Readers will find detailed information on fermenting vegetables; sugars into alcohol (meads, wines, and ciders); sour tonic beverages; milk; grains and starchy tubers; beers (and other grain-based alcoholic beverages); beans; seeds; nuts; fish; meat; and eggs, as well as growing mold cultures, using fermentation in agriculture, art, and energy production, and considerations for commercial enterprises. Sandor Katz has introduced what will undoubtedly remain a classic in food literature, and is the first--and only--of its kind."),
            new Book(1857993284, "Sophie's World", "Jostein Gaarder", "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1343459906l/10959.jpg", "One day fourteen-year-old Sophie Amundsen comes home from school to find in her mailbox two notes, with one question on each: \"Who are you?\" and \"Where does the world come from?\" From that irresistible beginning, Sophie becomes obsessed with questions that take her far beyond what she knows of her Norwegian village. Through those letters, she enrolls in a kind of correspondence course, covering Socrates to Sartre, with a mysterious philosopher, while receiving letters addressed to another girl. Who is Hilde? And why does her mail keep turning up? To unravel this riddle, Sophie must use the philosophy she is learning—but the truth turns out to be far more complicated than she could have imagined."),
            new Book(14017897, "Essays", "Michel de Montaigne", "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1303068837l/30733.jpg", "Reflections by the creator of the essay form, display the humane, skeptical, humorous, and honest views of Montaigne, revealing his thoughts on sexuality, religion, cannibals, intellectuals, and other unexpected themes. Included are such celebrated works as \"On Solitude,\" \"To Philosophize Is to Learn How to Die,\" and \"On Experience.\""),
            new Book(140449337, "Meditations", "Marcus Aurelius", "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1421618636l/30659.jpg", "Written in Greek, without any intention of publication, by the only Roman emperor who was also a philosopher, the Meditations of Marcus Aurelius (AD 121-180) offer a remarkable series of challenging spiritual reflections and exercises developed as the emperor struggled to understand himself and make sense of the universe.\n" +
                    "\n" +
                    "Ranging from doubt and despair to conviction and exaltation, they cover such diverse topics as the nature of moral virtue, human rationality, divine providence, and Marcus' own emotions.\n" +
                    "\n" +
                    "But while the Meditations were composed to provide personal consolation and encouragement, in developing his beliefs Marcus Aurelius also created one of the greatest of all works of philosophy: a timeless collection of extended meditations and short aphorisms that has been consulted and admired by statesmen, thinkers and readers through the centuries.")
        );
    }
}
